// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApplication.DataAccess;

namespace TestApplication.DataAccess.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20220717065153_AuthorModel")]
    partial class AuthorModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestApplication.Models.Author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "sandun"
                        },
                        new
                        {
                            id = 2,
                            name = "kashmir"
                        },
                        new
                        {
                            id = 3,
                            name = "jackob"
                        },
                        new
                        {
                            id = 4,
                            name = "jenny"
                        });
                });

            modelBuilder.Entity("TestApplication.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("authorid")
                        .HasColumnType("int");

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("due")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("authorid");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            authorid = 1,
                            created = new DateTime(2022, 7, 17, 12, 21, 52, 907, DateTimeKind.Local).AddTicks(9266),
                            description = " test descriptions",
                            due = new DateTime(2022, 7, 19, 12, 21, 52, 910, DateTimeKind.Local).AddTicks(8551),
                            status = 1,
                            title = "test"
                        },
                        new
                        {
                            Id = 2,
                            authorid = 1,
                            created = new DateTime(2022, 7, 17, 12, 21, 52, 911, DateTimeKind.Local).AddTicks(1214),
                            description = " second attempt",
                            due = new DateTime(2022, 7, 19, 12, 21, 52, 911, DateTimeKind.Local).AddTicks(1255),
                            status = 0,
                            title = "learn dotnet"
                        },
                        new
                        {
                            Id = 3,
                            authorid = 4,
                            created = new DateTime(2022, 7, 17, 12, 21, 52, 911, DateTimeKind.Local).AddTicks(1350),
                            description = " This is to learn dotnet",
                            due = new DateTime(2022, 7, 22, 12, 21, 52, 911, DateTimeKind.Local).AddTicks(1357),
                            status = 2,
                            title = "go home"
                        });
                });

            modelBuilder.Entity("TestApplication.Models.Todo", b =>
                {
                    b.HasOne("TestApplication.Models.Author", "author")
                        .WithMany()
                        .HasForeignKey("authorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
