// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApplication.DataAccess;

namespace TestApplication.DataAccess.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestApplication.Models.Author", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adressnb")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("street")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            id = 1,
                            adressnb = "162/4",
                            city = "Ambalangoda",
                            name = "sandun",
                            street = "Athvalagoda"
                        },
                        new
                        {
                            id = 2,
                            adressnb = "1678B",
                            city = "Los Angeles",
                            name = "kashmir",
                            street = "Mension Street"
                        },
                        new
                        {
                            id = 3,
                            adressnb = "54",
                            city = "Okhlama",
                            name = "jackob",
                            street = "Denist Street"
                        },
                        new
                        {
                            id = 4,
                            adressnb = "162/4",
                            city = "Sillycan Valley",
                            name = "jenny",
                            street = "FB Street"
                        });
                });

            modelBuilder.Entity("TestApplication.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("authorid")
                        .HasColumnType("int");

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<DateTime>("due")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("authorid");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            authorid = 1,
                            created = new DateTime(2022, 7, 17, 15, 39, 41, 966, DateTimeKind.Local).AddTicks(2121),
                            description = " test descriptions",
                            due = new DateTime(2022, 7, 19, 15, 39, 41, 968, DateTimeKind.Local).AddTicks(2895),
                            status = 1,
                            title = "test"
                        },
                        new
                        {
                            Id = 2,
                            authorid = 1,
                            created = new DateTime(2022, 7, 17, 15, 39, 41, 968, DateTimeKind.Local).AddTicks(6187),
                            description = " second attempt",
                            due = new DateTime(2022, 7, 19, 15, 39, 41, 968, DateTimeKind.Local).AddTicks(6247),
                            status = 0,
                            title = "learn dotnet"
                        },
                        new
                        {
                            Id = 3,
                            authorid = 4,
                            created = new DateTime(2022, 7, 17, 15, 39, 41, 968, DateTimeKind.Local).AddTicks(6413),
                            description = " This is to learn dotnet",
                            due = new DateTime(2022, 7, 22, 15, 39, 41, 968, DateTimeKind.Local).AddTicks(6426),
                            status = 2,
                            title = "go home"
                        });
                });

            modelBuilder.Entity("TestApplication.Models.Todo", b =>
                {
                    b.HasOne("TestApplication.Models.Author", "author")
                        .WithMany()
                        .HasForeignKey("authorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
